Model\Entity\Location:
    properties:
        name:
            - NotBlank: ~
        adress:
            - NotBlank: ~
        zip_code:
            - Regex:
                pattern: "/\d{5}/"
                message: Bad zip code
        city:
            - NotBlank: ~
        phone:
            - Regex:
                pattern: "/\d{10}/"
                message: Bad phone number

Model\Entity\Comment:
    properties:
        username:
            - NotBlank: ~
        body:
            - NotBlank: ~

Model\Entity\Party:
    properties:
        name:
            - NotBlank: ~
        date:
            - DateTime: ~